# A Docker Compose file for spinning up integration tests in CI
version: "3"
services:
  placement:
    image: daprio/dapr:1.0.1
    command: [ "./placement","-port","50006" ]
  redis:
    image: redis:latest
  state-test-client:
    build:
      dockerfile: images/grpc.Dockerfile
      context: .
      target: production
      args:
        BASE: tests/e2e/state-tests/client/
    depends_on:
      - placement
    ports:
      - 9501:80
  state-test-client-caddy:
    build:
      dockerfile: images/caddy.Dockerfile
      context: .
      args:
        BASE: tests/e2e/state-tests/client/
    depends_on:
      - state-test-client
    network_mode: service:state-test-client
  state-test-client-daprd:
    image: daprio/daprd:1.0.1
    command: [ "./daprd","-app-id","state-client-test","-app-port","80","-placement-host-address","placement:50006","-components-path","/components" ]
    volumes:
      - ./components:/components
    depends_on:
      - state-test-client
    network_mode: service:state-test-client
